# Could be better but it's whatever for now

name: Sync to Alpha

on:
  push:
    branches:
      - main
  # Enables manually triggering of Workflow with file synchronization option
  workflow_dispatch:
    inputs:
      sync:
        description: "File synchronization"
        required: true
        default: "delta"
  
jobs:
  upload:
    name: Sync Files
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - uses: actions/checkout@v2.1.0
        with: 
          fetch-depth: 0
      
      - name: Sync strippers
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: "sftp"
          remote-host: ${{ secrets.ALPHA_SFTP_HOST }}
          remote-port: ${{ secrets.ALPHA_SFTP_PORT }}
          remote-user: ${{ secrets.ALPHA_SFTP_USER }}
          remote-password: ${{ secrets.ALPHA_SFTP_PASSWORD }}
          local-path: "/addons/stripper/maps"
          remote-path: "/csgo/addons/stripper/maps"
          sync: delta
          debug: true
