name: Sync to Alpha

on:
  push:
    branches:
      - main
  # Enables manually triggering of Workflow with file synchronization option
  workflow_dispatch:
    inputs:
      sync:
        description: "File synchronization"
        required: true
        default: "delta"
  
jobs:
  upload:
    name: Sync Files
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - uses: actions/checkout@v2.1.0
        with: 
          fetch-depth: 0
      
      - name: 📂 Entwatch
        uses: pedrotski/FTP-Deploy-Action@1.1
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: 'entwatch/'
          server-dir: 'csgo/cfg/sourcemod/entwatch/maps/'
          

