name: Sync to Alpha

on:
  push:
    branches:
      - main
  # Enables manually triggering of Workflow
  workflow_dispatch:

jobs:
  sync-bosshp:
    name: Sync Bosshp
    runs-on: ubuntu-latest
    timeout-minutes: 6

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v3'
        with:
          fetch-depth: 0

      # restores files last modified times based on git history so only newer files are uploaded
      - name: 'Restore timestamps'
        uses: chetan/git-restore-mtime-action@v1

      - name: 📂 Sync Bosshp
        uses: wangyucode/sftp-upload-action@v1.4.5
        with:
          host: ${{ secrets.FTP_SERVER }}
          port: ${{ secrets.FTP_PORT }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: 'bosshp/'
          remoteDir: 'csgo/addons/sourcemod/configs/MapBossHP/'
          dryRun: false

  sync-entwatch:
    name: Sync Entwatch
    runs-on: ubuntu-latest
    timeout-minutes: 6

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v3'
        with:
          fetch-depth: 0

      - name: 'Restore timestamps'
        uses: chetan/git-restore-mtime-action@v1

      - name: 📂 Sync Entwatch
        uses: wangyucode/sftp-upload-action@v1.4.5
        with:
          host: ${{ secrets.FTP_SERVER }}
          port: ${{ secrets.FTP_PORT }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: 'entwatch/'
          remoteDir: 'csgo/cfg/sourcemod/entwatch/maps/'
          dryRun: false

  sync-map-cfg:
    name: Sync Map Configs
    runs-on: ubuntu-latest
    timeout-minutes: 6

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v3'
        with:
          fetch-depth: 0

      - name: 'Restore timestamps'
        uses: chetan/git-restore-mtime-action@v1

      - name: 📂 Sync Map Configs
        uses: wangyucode/sftp-upload-action@v1.4.5
        with:
          host: ${{ secrets.FTP_SERVER }}
          port: ${{ secrets.FTP_PORT }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: 'map-cfg'
          remoteDir: 'csgo/cfg/sourcemod/map-cfg'
          dryRun: false

  sync-stripper:
    name: Sync Stripper
    runs-on: ubuntu-latest
    timeout-minutes: 6

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v3'
        with:
          fetch-depth: 0

      - name: 'Restore timestamps'
        uses: chetan/git-restore-mtime-action@v1

      - name: 📂 Sync Stripper
        uses: wangyucode/sftp-upload-action@v1.4.5
        with:
          host: ${{ secrets.FTP_SERVER }}
          port: ${{ secrets.FTP_PORT }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: 'stripper/'
          remoteDir: 'csgo/addons/stripper/maps/'
          dryRun: false

  sync-vscripts:
    name: Sync Vscripts
    runs-on: ubuntu-latest
    timeout-minutes: 6

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v3'
        with:
          fetch-depth: 0

      - name: 'Restore timestamps'
        uses: chetan/git-restore-mtime-action@v1

      - name: 📂 Sync Vscripts
        uses: wangyucode/sftp-upload-action@v1.4.5
        with:
          host: ${{ secrets.FTP_SERVER }}
          port: ${{ secrets.FTP_PORT }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: 'vscripts/'
          remoteDir: 'csgo/scripts/vscripts/'
          dryRun: false