# Could be better but it's whatever for now

name: Sync to Alpha

on:
  push:
    branches:
      - master
  # Enables manually triggering of Workflow with file synchronization option
  workflow_dispatch:
    inputs:
      sync:
        description: "File synchronization"
        required: true
        default: "delta"
  
jobs:
  deploy-master:
    name: Sync Files
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2.1.0
        with: 
          fetch-depth: 0
      
      - name: Sync strippers
        uses: milanmk/actions-file-deployer@1.10
        with:
          remote-protocol: "sftp"
          remote-host: '${{ secrets.ALPHA_SFTP_HOST }}'
          remote-user: '${{ secrets.ALPHA_SFTP_USER }}'
          remote-password: '${{ secrets.ALPHA_SFTP_PASSWORD }}'
          local-path: 'addons/stripper/maps/'
          remote-path: '/csgo/addons/stripper/maps/'
          sync: full
